### ISSUE TITLE
Find and fix issue with github profile pages

### ISSUE THREAD

**Issue by lorey** [lorey/mlscraper#23]
* follower counts have no unique selector (need nth or something else)

**Comment by lorey** [comment]
* follower count matched by nth-child pseudoselector 42e19d25d5c21e20250d3f327f66a90b7846d57a
* image width and height fixed by aa1ac21a0ede6f4f6a4282fcb07f87d706186817

**Comment by lorey** [comment]
Test Case added in c3427b79a09d4ea4595ab775f8c267364975b60c

**Comment by jonashaag** [comment]
This is still broken for me, what am I doing that's different from your test case?

```py
import requests
from mlscraper.html import Page
from mlscraper.samples import Sample, TrainingSet
from mlscraper.training import train_scraper

jonas_url = "https://github.com/jonashaag"
resp = requests.get(jonas_url)
resp.raise_for_status()

page = Page(resp.content)
sample = Sample(
    page,
    {
        "name": "Jonas Haag",
        "followers": "329",
        "company": "@Quantco",
        "twitter": "@_jonashaag",
        "username": "jonashaag",
        "nrepos": "282",
    },
)

training_set = TrainingSet()
training_set.add_sample(sample)

scraper = train_scraper(training_set)

resp = requests.get("https://github.com/lorey")
result = scraper.get(Page(resp.content))
print(result)
```

**Comment by jonashaag** [comment]
Are you testing with a HTML dump with login maybe?
